sudo: false
language: python

python:
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install --upgrade pip wheel setuptools
  - pip install coveralls tox-travis

before_script:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/alexandriadocs_cli

script:
  - tox
  - rstcheck README.rst

after_success:
  - coveralls
